export const generateNickname = (): string => {
  const adjectives: string[] = [
    'Frosty',
    'Fiery',
    'Electric',
    'Shadow',
    'Mystic',
    'Thunder',
    'Icy',
    'Swift',
    'Crimson',
    'Golden',
    'Stormy',
    'Lunar',
    'Solar',
    'Phantom',
    'Radiant',
    'Infernal',
    'Celestial',
    'Vivid',
    'Rogue',
    'Twisted',
    'Majestic',
    'Cosmic',
    'Glacial',
    'Wild',
    'Brave',
    'Turbo',
    'Velvet',
    'Atomic',
    'Echo',
    'Daring',
  ]

  const animals: string[] = [
    'Bear',
    'Wolf',
    'Fox',
    'Falcon',
    'Dragon',
    'Tiger',
    'Panther',
    'Phoenix',
    'Eagle',
    'Serpent',
    'Raven',
    'Shark',
    'Lynx',
    'Cheetah',
    'Cobra',
    'Bison',
    'Jackal',
    'Owl',
    'Leopard',
    'Puma',
    'Viper',
    'Stallion',
    'Kraken',
    'Hawk',
    'Tundra',
    'Raptor',
    'Basilisk',
    'Griffin',
    'Scorpion',
    'Yeti',
  ]

  const getRandomElement = (arr: string[]): string =>
    arr[Math.floor(Math.random() * arr.length)]

  return `${getRandomElement(adjectives)}${getRandomElement(animals)}`
}
