version: '3.8'

services:
  redis:
    image: redis:8.0.1
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  mongodb:
    image: mongo:8.0.9
    container_name: mongodb
    hostname: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db

volumes:
  redis:
    driver: local
  mongodb:
    driver: local
