#!/usr/bin/env sh

action=$1
env=$2

if [ "$action" != "build" ] && [ "$action" != "deploy" ] && [ "$action" != "deps" ]; then
  echo "Error: Invalid action. Please specify either 'build', 'deploy' or 'deps'."
  exit 1
fi

if [ "$action" = "deploy" ] && [ "$env" != "local" ] && [ "$env" != "production" ]; then
  echo "Error: Invalid environment. Please specify either 'local' or 'production'."
  exit 1
fi

if [ "$action" = "build" ]; then
  docker-compose build quiz-service quiz
fi

if [ "$action" = "deps" ]; then
    docker-compose up -d redis mongodb
fi

if [ "$action" = "deploy" ]; then
  if [ "$env" = "local" ]; then
    docker-compose up -d --build
  fi

  if [ "$env" = "production" ]; then
    docker-compose build quiz-service quiz

    docker image tag emilhornlund/quiz:latest 192.168.0.65:9500/emilhornlund/quiz:latest
    docker image push 192.168.0.65:9500/emilhornlund/quiz:latest

    docker image tag emilhornlund/quiz-service:latest 192.168.0.65:9500/emilhornlund/quiz-service:latest
    docker image push 192.168.0.65:9500/emilhornlund/quiz-service:latest
  fi
fi
