export enum GameEventType {
  GameHeartbeat = 'GAME_HEARTBEAT',
  GameLoading = 'GAME_LOADING',
  GameLobbyHost = 'GAME_LOBBY_HOST',
  GameLobbyPlayer = 'GAME_LOBBY_PLAYER',
  GameBeginHost = 'GAME_BEGIN_HOST',
  GameBeginPlayer = 'GAME_BEGIN_PLAYER',
  GameQuestionPreviewHost = 'GAME_QUESTION_PREVIEW_HOST',
  GameQuestionPreviewPlayer = 'GAME_QUESTION_PREVIEW_PLAYER',
  GameQuestionHost = 'GAME_QUESTION_HOST',
  GameQuestionPlayer = 'GAME_QUESTION_PLAYER',
  GameAwaitingResultPlayer = 'GAME_AWAITING_RESULT_PLAYER',
  GameLeaderboardHost = 'GAME_LEADERBOARD_HOST',
  GameLeaderboardPlayer = 'GAME_LEADERBOARD_PLAYER',
  GameResultHost = 'GAME_RESULT_HOST',
  GameResultPlayer = 'GAME_RESULT_PLAYER',
  GamePodiumHost = 'GAME_PODIUM_HOST',
  GamePodiumPlayer = 'GAME_PODIUM_PLAYER',
}
