export const COLLECTION_NAME_DISCOVERY_SNAPSHOTS = 'discovery_snapshots'
export const COLLECTION_NAME_GAMES = 'games'
export const COLLECTION_NAME_GAME_RESULTS = 'game_results'
export const COLLECTION_NAME_QUIZZES = 'quizzes'
export const COLLECTION_NAME_QUIZ_RATINGS = 'quiz_ratings'
export const COLLECTION_NAME_TOKENS = 'tokens'
export const COLLECTION_NAME_USERS = 'users'
