---
apiVersion: v1
kind: Service
metadata:
  name: quiz
  namespace: quiz
spec:
  selector:
    app: quiz
  type: LoadBalancer
  ports:
    - name: quiz-port
      protocol: TCP
      port: 80
      targetPort: 80
  loadBalancerIP: 192.168.0.211
