---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz
  namespace: quiz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz
  template:
    metadata:
      labels:
        app: quiz
        name: quiz
    spec:
      nodeSelector:
        node-type: worker
      containers:
        - name: quiz
          image: registry.cluster.local:5000/emilhornlund/quiz:bae3bc0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: NODE_ENV
              value: "production"
            - name: SERVER_PORT
              value: "80"
            - name: VITE_QUIZ_SERVICE_URL
              value: "/quiz-service/api"
            - name: VITE_BASE_URL
              value: "https://quiz.emilhornlund.com"
            - name: QUIZ_SERVICE_PROXY
              value: "http://quiz-service.quiz.svc.cluster.local:8080/api"
          ports:
            - name: quiz-service
              containerPort: 80
