---
apiVersion: v1
kind: Service
metadata:
  name: quiz-service
  namespace: quiz
spec:
  selector:
    app: quiz-service
  type: LoadBalancer
  ports:
    - name: quiz-service-port
      protocol: TCP
      port: 8080
      targetPort: 8080
  loadBalancerIP: 192.168.0.210
