export enum QuestionFieldType {
  CommonDuration = 'DURATION',
  CommonInfo = 'INFO',
  CommonMedia = 'MEDIA',
  CommonPoints = 'POINTS',
  CommonQuestion = 'QUESTION',
  CommonType = 'TYPE',
  MultiChoiceOptions = 'MULTI_CHOICE_OPTIONS',
  Pin = 'PIN',
  PinTolerance = 'PIN_TOLERANCE',
  PuzzleValues = 'PUZZLE_VALUES',
  Range = 'RANGE',
  RangeCorrect = 'CORRECT',
  RangeMargin = 'MARGIN',
  RangeMax = 'MAX',
  RangeMin = 'MIN',
  TrueFalseOptions = 'TRUE_FALSE_OPTIONS',
  TypeAnswerOptions = 'TYPE_ANSWER_OPTIONS',
}
