# .github/workflows/docker-build-and-push.yml
name: Build & Push Docker Image
permissions:
  contents: read
on:
  workflow_call:
    secrets:
      REGISTRY_USER:
        required: true
      REGISTRY_PASS:
        required: true
    outputs:
      short_sha:
        description: "Short git SHA for this run"
        value: ${{ jobs.prepare.outputs.short_sha }}

jobs:
  prepare:
    runs-on: self-hosted
    outputs:
      short_sha: ${{ steps.get_sha.outputs.short_sha }}
    steps:
      - uses: actions/checkout@v4
      - id: get_sha
        run: |
          echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

  docker_build_and_push:
    needs: prepare
    runs-on: self-hosted
    strategy:
      matrix:
        service:
          - quiz
          - quiz-service
    env:
      REGISTRY_HOST: emils-nuc-server:5000
      SHORT_SHA: ${{ needs.prepare.outputs.short_sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Login to Private Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build & Push ${{ matrix.service }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./packages/${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY_HOST }}/${{ matrix.service }}:${{ env.SHORT_SHA }}
