# .github/workflows/main.yml
name: Main
permissions: {}
on:
  push:
    branches:
      - main
      - "release/**"

jobs:
  build:
    permissions:
      contents: read
    uses: ./.github/workflows/build.yml
    secrets: inherit

  docker-build-and-push:
    needs: build
    permissions:
      contents: read
    uses: ./.github/workflows/docker-build-and-push.yml
    secrets: inherit

  deploy-beta:
    needs: docker-build-and-push
    uses: ./.github/workflows/deploy.yml
    with:
      target_env: beta
      tag: ${{ needs.docker-build-and-push.outputs.short_sha }}
    secrets:
      INFRA_REPO_PAT: ${{ secrets.INFRA_REPO_PAT }}
      QUIZ_PORTAINER_BETA_WEBHOOK: ${{ secrets.QUIZ_PORTAINER_BETA_WEBHOOK }}
      QUIZ_SERVICE_PORTAINER_BETA_WEBHOOK: ${{ secrets.QUIZ_SERVICE_PORTAINER_BETA_WEBHOOK }}

  deploy-production:
    needs:
      - docker-build-and-push
      - deploy-beta
    uses: ./.github/workflows/deploy.yml
    with:
      target_env: prod
      tag: ${{ needs.docker-build-and-push.outputs.short_sha }}
    secrets:
      INFRA_REPO_PAT: ${{ secrets.INFRA_REPO_PAT }}
      QUIZ_PORTAINER_PRODUCTION_WEBHOOK: ${{ secrets.QUIZ_PORTAINER_PRODUCTION_WEBHOOK }}
      QUIZ_SERVICE_PORTAINER_PRODUCTION_WEBHOOK: ${{ secrets.QUIZ_SERVICE_PORTAINER_PRODUCTION_WEBHOOK }}
