name: Main
on:
  push:
    branches:
      - 'main'
      - 'release/**'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  release:
    needs: build
    uses: ./.github/workflows/release.yml
    secrets: inherit
