# .github/workflows/prod-deploy.yml
name: Prod Deploy
permissions: {}
on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
    uses: ./.github/workflows/build.yml
    secrets: inherit

  docker-build-and-push:
    needs: build
    permissions:
      contents: read
    uses: ./.github/workflows/docker-build-and-push.yml
    secrets: inherit

  deploy-production:
    needs: docker-build-and-push
    uses: ./.github/workflows/deploy.yml
    with:
      target_env: prod
      tag: ${{ needs.docker-build-and-push.outputs.short_sha }}
    secrets:
      INFRA_REPO_PAT: ${{ secrets.INFRA_REPO_PAT }}
      QUIZ_PORTAINER_PRODUCTION_WEBHOOK: ${{ secrets.QUIZ_PORTAINER_PRODUCTION_WEBHOOK }}
      QUIZ_SERVICE_PORTAINER_PRODUCTION_WEBHOOK: ${{ secrets.QUIZ_SERVICE_PORTAINER_PRODUCTION_WEBHOOK }}

  sentry-release:
    needs: deploy-production
    permissions:
      contents: read
    uses: ./.github/workflows/sentry-release.yml
    with:
      environment: prod
      release: ${{ github.sha }}
    secrets:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
