# .github/workflows/pull-request.yml
name: Pull-Request
permissions: {}
on:
  pull_request:
    branches: ['**']

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/build.yml
