# .github/workflows/pull_request.yml
name: Pull-Request
permissions:
  contents: read
on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
