# .github/workflows/pull-request.yml
name: Pull-Request
permissions: {}
on:
  pull_request:
    branches: ['**']

jobs:
  build:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    permissions:
      contents: read
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit

  mark-required-check:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    needs: build
    runs-on: self-hosted
    permissions:
      statuses: write
      contents: read
    steps:
      - name: Mark required check as success
        uses: actions/github-script@v8
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: 'success',
              context: 'pr/required',
              description: 'PR workflow passed'
            })
