# .github/workflows/pull_request.yml
name: Pull-Request
permissions: {}
on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    permissions:
      contents: read
    uses: ./.github/workflows/build.yml
    secrets: inherit
